# File generated by cdo from CONTRIBUTING.md; DO NOT EDIT.

SHELL=bash
.SHELLFLAGS=-e -o pipefail -c

.PHONY: __help__
__help__:
	@echo 'Usage: make [target]'
	@echo ''
	@echo 'Targets:'
	@echo '  all      Run relevant tasks'
	@echo '  build    Build custom k6 with extension'
	@echo '  clean    Clean the working directory'
	@echo '  doc      Generate API documentation'
	@echo '  format   Format the go source codes'
	@echo '  it       Run the integration tests'
	@echo '  lint     Run the linter'
	@echo '  makefile Generate the Makefile'
	@echo '  readme   Update README.md'
	@echo '  security Run security checks'
	@echo '  test     Run the tests'

# Run relevant tasks
.PHONY: all
all: clean format lint security test build it doc readme makefile

# Build custom k6 with extension
.PHONY: build
build: 
	@(\
		xk6 build --with github.com/grafana/xk6-example=.;\
	)

# Clean the working directory
.PHONY: clean
clean: 
	@(\
		rm -rf ./k6 ./coverage.txt ./build ./node_modules ./bun.lockb ./.golangci.yml;\
	)

# Generate API documentation
.PHONY: doc
doc: 
	@(\
		bun x typedoc --out build/docs;\
	)

# Format the go source codes
.PHONY: format
format: 
	@(\
		go fmt ./...;\
	)

# Run the integration tests
.PHONY: it
it: 
	@(\
		./k6 run test/smoke.test.js;\
	)

# Run the linter
.PHONY: lint
lint: 
	@(\
		K6_CI_REF=$$(grep -oE 'grafana/k6-ci/[^@[:space:]]+@[A-Za-z0-9._/-]+' .github/workflows/validate.yml | head -n1 | cut -d@ -f2);\
		curl -fsSL "https://raw.githubusercontent.com/grafana/k6-ci/$${K6_CI_REF}/.golangci.yml" -o .golangci.yml;\
		go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@$$(head -n1 .golangci.yml | tr -d '# ') run --config=.golangci.yml ./...;\
		xk6 lint;\
	)

# Generate the Makefile
.PHONY: makefile
makefile: 
	@(\
		cdo --makefile Makefile;\
	)

# Update README.md
.PHONY: readme
readme: 
	@(\
		mdcode update;\
	)

# Run security checks
.PHONY: security
security: 
	@(\
		gosec -quiet ./...;\
		govulncheck ./...;\
	)

# Run the tests
.PHONY: test
test: 
	@(\
		go test -count 1 -race -coverprofile=coverage.txt -timeout 60s ./...;\
	)
